input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 5000
    codec => json_lines
    type => "microcontroller-service"
  }
  
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 5001
    codec => json_lines
    type => "application-service"
  }
}

filter {
  if [type] in ["microcontroller-service", "application-service"] {
    json {
      source => "message"
      target => "[parsed]"
      remove_field => ["message"]
      skip_on_invalid_json => true
    }
    
    if [parsed] {
      mutate {
        add_field => {
          "log_level" => "%{[parsed][level]}"
          "log_message" => "%{[parsed][message]}"
          "service_name" => "%{[parsed][service_name]}"
          "trace_id" => "%{[parsed][trace_id]}"
          "span_id" => "%{[parsed][span_id]}"
        }
        remove_field => ["parsed"]
      }
    }
  }
  
  mutate {
    uppercase => ["log_level"]
    remove_field => ["host", "@version", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://verdant-elasticsearch:9200"] # Menggunakan nama container ES Anda
    index => "%{type}-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
  
  stdout {
    codec => rubydebug
  }
}