# Application
spring.application.name=security-service
server.port=8084

# User
userservice.base-url=http://localhost:8083

# JWT
jwt.secret=Jcau6mPiMUpCK3NflMzbvcgr0oVkILNhg7sb29Kh0yP
jwt.expiration=86400000